---
- hosts: all
  tasks:
  - name: Assert local prerequisites are met
    import_tasks: ./check_local_prerequisites.yml
    when: "'localhost' in group_names"
    tags:
    - check_local_prerequisites
  
  - name: Root CA
    import_tasks: ./root_ca.yml
    when: "'localhost' in group_names"
    tags:
    - generate_the_root_ca    


  - name: Download etcd
    become: yes
    script: ./scripts/download_etcd {{ etcd3_version }}
    args:
      creates: /tmp/.download_etcd
    when: "'etcd_peers' in group_names"
    tags:
    - download_etcd


  - name: Install a CRI-compatible container runtime
    import_tasks: ./install_container_runtime.yml
    when: "'k8s_nodes' in group_names"
    tags:
    - install_container_runtime


  - name: Download kubernetes control plane components
    become: yes
    script: ./scripts/download_kubernetes_control_plane {{ kubernetes_version }}
    args:
      creates: /tmp/.download_kubernetes_control_plane
    when: "'masters' in group_names"
    tags:
    - download_kubernetes
    - download_kubernetes_control_plane
 
 
  - name: Download kubernetes worker components
    become: yes
    script: ./scripts/download_kubernetes_worker_components {{ kubernetes_version }}
    args:
      creates: /tmp/.download_kubernetes_worker_components
    when: "'workers' in group_names"
    tags:
    - download_kubernetes
    - download_kubernetes_worker_components

